# Header
menu:
  首页: /#blog
  归档: /archives
  随笔: /lifes
  关于: /abouts


# Site favicon
favicon: /favicon.png

# Site logo
logo: /avatar.png

# Enable Mathjax
mathjax: true

# Enable awesome-toc
awesome_toc: true

# Enable githubRepoWidget
github_repo_widget: false